### ISSUE TITLE
Helm install/upgrade fails when setting router deployment annotation in values.yaml

### ISSUE THREAD

**Issue by mhulscher** [deis/workflow#689]
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
```
Client: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}

```
```
# inside the values.yaml
  deployment_annotations:
    router.deis.io/nginx.defaultWhitelist: "127.0.0.1, 8.8.8.8"
```

Executing the following command:
```
$ helm upgrade deis-workflow-2 deis/workflow -f values.yaml
Error: UPGRADE FAILED: unable to decode "": [pos 236]: json: expect char '"' but got char 't'
```

Removing the annotation in the values.yaml allows the upgrade to pass. Am I perhaps doing something wrong?

**Comment by bacongobbler** [comment]
can you provide your full values.yaml with sensitive information redacted? Seems similar to https://github.com/deis/builder/issues/460.

**Comment by bacongobbler** [comment]
ping, is this still relevant now that deis/builder#460 has been resolved?

**Comment by mhulscher** [comment]
This is still relevant. I will provide an example configuration file.

**Comment by Bregor** [comment]
Are you sure error is relevant to annotations?
Check position 236 in `values.yaml`.
I always have this error in `kubectl apply -f ...` when my manifest contains something like:

    some_key: true

Changing `true` to `"true"` (with explicit quotes) works like a charm in this cases.

**Comment by mhulscher** [comment]
Problem persists. I just upgraded another DeisWF installation from 2.9.0 tot 2.10.0. This time a Kubernetes 1.4.8 cluster. Below are the values with REDACTED configuration. The deployment only succeeds if I comment out the deployment_annotations. Quoting/unquoting key/values does not help. I have tried removing existing annotations from the deploy/deis-router, that didn't help. I tried upgrading with only a single annotation in the values.yaml, but no matter how many I enable/disable the upgrade will fail. Fortunately, upgrading without annotations does not clear existing annotations on the router deployment object.

```
---
# This is the global configuration file for Workflow

global:
  # Set the storage backend
  #
  # Valid values are:
  # - s3: Store persistent data in AWS S3 (configure in S3 section)
  # - azure: Store persistent data in Azure's object storage
  # - gcs: Store persistent data in Google Cloud Storage
  # - minio: Store persistent data on in-cluster Minio server
  storage: gcs

  # Set the location of Workflow's PostgreSQL database
  #
  # Valid values are:
  # - on-cluster: Run PostgreSQL within the Kubernetes cluster (credentials are generated
  #   automatically; backups are sent to object storage
  #   configured above)
  # - off-cluster: Run PostgreSQL outside the Kubernetes cluster (configure in database section)
  database_location: "off-cluster"

  # Set the location of Workflow's logger-specific Redis instance
  #
  # Valid values are:
  # - on-cluster: Run Redis within the Kubernetes cluster
  # - off-cluster: Run Redis outside the Kubernetes cluster (configure in loggerRedis section)
  logger_redis_location: "on-cluster"

  # Set the location of Workflow's influxdb cluster
  #
  # Valid values are:
  # - on-cluster: Run Influxdb within the Kubernetes cluster
  # - off-cluster: Influxdb is running outside of the cluster and credentials and connection information will be provided.
  influxdb_location: "on-cluster"
  # Set the location of Workflow's grafana instance
  #
  # Valid values are:
  # - on-cluster: Run Grafana within the Kubernetes cluster
  # - off-cluster: Grafana is running outside of the cluster
  grafana_location: "on-cluster"

  # Set the location of Workflow's Registry
  #
  # Valid values are:
  # - on-cluster: Run registry within the Kubernetes cluster
  # - off-cluster: Use registry outside the Kubernetes cluster (example: dockerhub,quay.io,self-hosted)
  # - ecr: Use Amazon's ECR
  # - gcr: Use Google's GCR
  registry_location: "gcr"
  # The host port to which registry proxy binds to
  host_port: 5555
  # Prefix for the imagepull secret created when using private registry
  secret_prefix: "private-registry"


s3:
  # Your AWS access key. Leave it empty if you want to use IAM credentials.
  accesskey: ""
  # Your AWS secret key. Leave it empty if you want to use IAM credentials.
  secretkey: ""
  # Any S3 region
  region: "us-west-1"
  # Your buckets.
  registry_bucket: "your-registry-bucket-name"
  database_bucket: "your-database-bucket-name"
  builder_bucket: "your-builder-bucket-name"

azure:
  accountname: "YOUR ACCOUNT NAME"
  accountkey: "YOUR ACCOUNT KEY"
  registry_container: "your-registry-container-name"
  database_container: "your-database-container-name"
  builder_container: "your-builder-container-name"

gcs:
  # key_json is expanded into a JSON file on the remote server. It must be
  # well-formatted JSON data.
  key_json: "REDACTED"
  registry_bucket: "REDACTED"
  database_bucket: "REDACTED"
  builder_bucket: "REDACTED"

swift:
  username: "Your OpenStack Swift Username"
  password: "Your OpenStack Swift Password"
  authurl: "Swift auth URL for obtaining an auth token"
  # Your OpenStack tenant name if you are using auth version 2 or 3.
  tenant: ""
  authversion: "Your OpenStack swift auth version"
  registry_container: "your-registry-container-name"
  database_container: "your-database-container-name"
  builder_container: "your-builder-container-name"

# Set the default (global) way of how Application (your own) images are
# pulled from within the Controller.
# This can be configured per Application as well in the Controller.
#
# This affects pull apps and git push (slugrunner images) apps
#
# Values values are:
# - Always
# - IfNotPresent
controller:
  app_pull_policy: "IfNotPresent"
  # Possible values are:
  # enabled - allows for open registration
  # disabled - turns off open registration
  # admin_only - allows for registration by an admin only.
  registration_mode: "admin_only"

database:
  # The username and password to be used by the on-cluster database.
  # If left empty they will be generated using randAlphaNum
  username: ""
  password: ""
  # Configure the following ONLY if using an off-cluster PostgreSQL database
  postgres:
    name: "REDACTED"
    username: "REDACTED"
    password: "REDACTED"
    host: "REDACTED"
    port: "5432"

redis:
  # Configure the following ONLY if using an off-cluster Redis instance for logger
  db: "0"
  host: "redis host"
  port: "redis port"
  password: "redis password" # "" == no password

fluentd:
  syslog:
    # Configure the following ONLY if using Fluentd to send log messages to both
    # the Logger component and external syslog endpoint
    # external syslog endpoint url
    host: ""
    # external syslog endpoint port
    port: ""

monitor:
  grafana:
    user: "admin"
    password: "admin"
  # Configure the following ONLY if using an off-cluster Influx database
  influxdb:
    url: "my.influx.url"
    database: "kubernetes"
    user: "user"
    password: "password"

registry-token-refresher:
  # Time in minutes after which the token should be refreshed.
  # Leave it empty to use the default provider time.
  token_refresh_time: ""
  off_cluster_registry:
    hostname: ""
    organization: ""
    username: ""
    password: ""
  ecr:
    # Your AWS access key. Leave it empty if you want to use IAM credentials.
    accesskey: ""
    # Your AWS secret key. Leave it empty if you want to use IAM credentials.
    secretkey: ""
    # Any S3 region
    region: "us-west-2"
    registryid: ""
    hostname: ""
  gcr:
    key_json: "REDACTED"
    hostname: "eu.gcr.io"

router:
  dhparam: ""
  # Any custom router annotations(https://github.com/deis/router#annotations)
  # which need to be applied can be specified as key-value pairs under "deployment_annotations"
  deployment_annotations:
    router.deis.io/nginx.defaultWhitelist: "REDACTED"
    router.deis.io/nginx.enforceWhitelists: "true"
    router.deis.io/nginx.platformDomain: "REDACTED"
    router.deis.io/nginx.proxyRealIpCidrs: "REDACTED"
    router.deis.io/nginx.serverNameHashBucketSize: "128"
    router.deis.io/nginx.whitelistMode: "extend"

  # Any custom annotations for k8s services like http://kubernetes.io/docs/user-guide/services/#ssl-support-on-aws
  # which need to be applied can be specified as key-value pairs under "service_annotations"
  service_annotations:
    #<example-key>: <example-value>

  # Enable to pin router pod hostPort when using minikube or vagrant
  host_port:
    enabled: true

  # Service type default to LoadBalancer 
  service_type: NodePort

workflow-manager:
  versions_api_url: https://versions.deis.com
  doctor_api_url: https://doctor.deis.com
```

**Comment by Bregor** [comment]
@mhulscher 

    # Enable to pin router pod hostPort when using minikube or vagrant
    host_port:
      enabled: true

Unquoted `true`

**Comment by mhulscher** [comment]
Booleans are a type in YAML. Also quoting the "true" causes the deis-upgrade job to fail with a ErrImagePullBackoff

**Comment by Bregor** [comment]
I mean something like this:

        apiVersion: extensions/v1beta1
        kind: Deployment
        metadata:
          annotations:
            deployment.kubernetes.io/revision: "15"
            prometheus.io/scrape: "true"

Unquoted `true` here will fire an error with `kubectl apply`

**Comment by Bregor** [comment]
So in fact `helm upgrade` just generates proper manifest from templates and applies them.
You can see templates with `helm fetch deis/workflow --untar`. But main problem is we don't know which manifest precisely is failing to apply...

**Comment by bacongobbler** [comment]
`helm lint` shows the error with values.yaml:

```
><> helm fetch deis/workflow --untar
><> vim workflow/values.yaml
><> helm lint workflow/
2017/01/16 15:44:33 warning: skipped value for deployment_annotations: Not a table.
2017/01/16 15:44:33 warning: skipped value for deployment_annotations: Not a table.
```

This is an actually interesting issue. It turns out that the downstream router chart's values.yaml mangles this:

```
><> cat workflow/charts/router/values.yaml
org: "deis"
pull_policy: "IfNotPresent"
docker_tag: v2.8.1
platform_domain: ""
dhparam: ""
# limits_cpu: "100m"
# limits_memory: "50Mi"

# Any custom router annotations(https://github.com/deis/router#annotations)
# which need to be applied can be specified as key-value pairs under "deployment_annotations"
deployment_annotations:
  #<example-key>: <example-value>

# Any custom annotations for k8s services like http://kubernetes.io/docs/user-guide/services/#ssl-support-on-aws
# which need to be applied can be specified as key-value pairs under "service_annotations"
service_annotations:
  #<example-key>: <example-value>

# Enable to pin router pod hostPort when using minikube or vagrant
host_port:
  enabled: true

# Service type default to LoadBalancer 
# service_type: LoadBalancer
```

If I remove the `deployment_annotations` (and `service_annotations`) field completely from that values.yaml, `helm lint` passes. Can you try that and try re-deploy? I'm on a plane at the moment so I don't have access to a kube cluster handy to test.

ping @technosophos, do you know if this is a known helm bug or something we should file a bug and a fix for?

**Comment by mhulscher** [comment]
Removing `deployment_annotations` and `service_annotations` still allows for deployment. Also doesn't strip existing annotations from the deployment object.
